import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cafe.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11001.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11002.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11003.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11004.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11005.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11006.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11007.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11008.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11009.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11010.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11011.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11012.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11013.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11014.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11015.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11016.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11017.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11018.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11019.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11020.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11021.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11022.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11023.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.bois_054}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.bois_055}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.bois_089_Room_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.bois_110_Room_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.d671effe7f2cd3fb8e0c119e09825243}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.enduit_004_Room_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['700-nw_ovcol81592bcolpic05contpic10']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.enduit_004_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.faience_041_ovcol999999colpic12contpic01_Room_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.gris_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.gris_004_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.hotte_001___material__177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.hotte_001___material__178}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.hotte_001___material__179}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials['kisspng-pizza-knight-italian-cuisine-vegetarian-cuisine-fo-food']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.kitchen_classic_style_base_cabinet_007___phong2sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.kitchen_classic_style_base_cabinet_007___phong8sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.beige_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.kitchen_classic_style_base_corner_001___phong2sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.kitchen_classic_style_base_corner_001___phong8sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.kitchen_classic_style_dishwasher_000___phong5sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.kitchen_classic_style_dishwasher_000___phong8sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.kitchen_classic_style_dishwasher_000___phong9sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_35.geometry}
          material={materials.kitchen_classic_style_double_oven_000___phong4sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.kitchen_classic_style_double_oven_000___phong5sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials.kitchen_classic_style_double_oven_000___phong6sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials.kitchen_classic_style_double_oven_000___phong7sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.kitchen_classic_style_double_oven_000___vitre}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.beige_004_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials.lambris_ext_003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.lambris_ext_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.lavabo_004___lambert3sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.lavabo_004___phong1sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials.makaroniiztverdixsortovpshenitsikakievib_7ff8e298}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.meridienne_001___bis_mat_metalbasique004sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials.metal_rouille}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_48.geometry}
          material={materials.mur_vegetal_off___phong150}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials.mur_vegetal_off___phong151}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.beige_005_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.mur_vegetal_off___phong30}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.mur_vegetal_off___phong31}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.ocre_001_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials.orange_003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.pack_002_sdb_deroule_papier___01___defaulta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials.pack_002_sdb_deroule_papier___01___defaulte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials.pack_002_sdb_deroule_papier___01___defaultz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.pack_003_cuisine_001_table___mat_pack_003_cuisine_001_table_tab}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.beige_006_Wall_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.pack_004_salon_002_tableau___enduit1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.pack_005_salle_a_manger_armoire___nopaint_bouteilles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials.pack_005_salle_a_manger_armoire___poignees}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.plante_interieur_off___bis_palmier_tronc2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials.plante_interieur_off___phong56}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials.plante_interieur_off___phong57}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.plante_interieur_off___phong80}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials.porte_009___d}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.blanc_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials.porte_009___p}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.porte_022___mat_vitresg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_72.geometry}
          material={materials.poubelle_002___phong1sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.poubelle_002___poubelle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_74.geometry}
          material={materials.s1200_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials.tissus_089}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_77.geometry}
          material={materials.tissus_089_ovcola0a3cccolpic00contpic03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.vase_fleur_off___phong94}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8001.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8002.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8003.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8008.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8009.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8010.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8011.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8012.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8013.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8014.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8015.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8016.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8017.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8018.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8019.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8020.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8021.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8022.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8023.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8024.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8025.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8026.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8027.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8028.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8029.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8030.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8031.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8032.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8033.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8038.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8039.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8040.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8041.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_80.geometry}
          material={materials.vitrine_000___mat_vitrine_verre}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_81.geometry}
          material={materials.wc_004___wc_004_blinn1sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_82.geometry}
          material={materials.wc_004___wc_004_blinn3sg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_83.geometry}
          material={materials.ws13d0020}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_84.geometry}
          material={materials['--_ovcol6b5a2ecolpic06contpic09']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_85.geometry}
          material={materials['-------76810378']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9001.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9002.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9003.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9004.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9005.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9006.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9007.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9008.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9009.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9010.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9011.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9012.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9013.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9014.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9015.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9016.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9017.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9018.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9019.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9020.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9021.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9022.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9023.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9024.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9025.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9026.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9027.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9028.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9029.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9030.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9031.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9032.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9033.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9042.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9043.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9044.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9045.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9046.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9047.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9048.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9049.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9054.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9055.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SOFA01_TABLE01.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SOFA01_TABLE02.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SOFA01_TABLE03.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SOFA02_TABLE02.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SOFA02_TABLE03.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56_1.geometry}
          material={materials.pack_004_cuisine_001_chaise___pied}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56_2.geometry}
          material={materials.pack_004_cuisine_001_chaise___rond}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56_3.geometry}
          material={materials.pack_004_cuisine_001_chaise___tour}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56_4.geometry}
          material={materials.pack_004_cuisine_001_chaise___tubes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56_5.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16008.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16008_1.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16064.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16064_1.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16016.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16016_1.geometry}
          material={materials.bleu_012}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58019.geometry}
          material={materials.pack_004_cuisine_001_chaise___tour}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58019_1.geometry}
          material={materials.bois_046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58019_2.geometry}
          material={materials.pack_004_cuisine_001_chaise___tubes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58019_3.geometry}
          material={materials.pack_004_cuisine_001_chaise___pied}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58019_4.geometry}
          material={materials.pack_004_cuisine_001_chaise___rond}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16001.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16001_1.geometry}
          material={materials.bleu_012}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16056.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16056_1.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16024.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16024_1.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16048.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16048_1.geometry}
          material={materials.bleu_012}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16032.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16032_1.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16072.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16072_1.geometry}
          material={materials.bleu_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16040.geometry}
          material={materials.eames_chair_dining_2____eames_chair_dinning_bwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16040_1.geometry}
          material={materials.bleu_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73_1.geometry}
          material={materials.tissus_078}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73_2.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76_1.geometry}
          material={materials.tissus_096}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76_2.geometry}
          material={materials.meridienne_001___mat_tissus078_bissg}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cafe.glb')
